name: build-and-deploy
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: tyreesamurai/ci-templates/.github/workflows/deploy.yml@main
    with:
      image_name: tyreesamurai/recipes-web # pushed to ghcr.io/tyreesamurai/recipes-web
      service_dir: /srv/apps/recipes # where compose.yaml lives on the server
    secrets: inherit
