name: build-and-deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: tyreesamurai/ci-templates/.github/workflows/deploy.yml@main
    with:
      image_name: tyreesamurai/recipes
      context: .
      dockerfile: Dockerfile
      namespace: recipes
      deployment: recipes
      kube_context: k3d-home
      secret_name: recipes-env
    secrets: inherit
